### ISSUE TITLE
Webviz failing while using tab instead of spaces

### ISSUE THREAD

**Issue by runemorten** [equinor/webviz-config#129]
Realized I had used tab instead of spaces in my webviz.yaml file. It was difficult to see what was the problem with my webviz.yaml file based on the error message I got:

"There is something wrong in the configuration file blabjorn_webviz.yaml. The typo is probably somewhere around line 33. Fix the error and save the configuration file in  order to trigger a new rebuild."

**Comment by anders-kiaer** [comment]
Thanks @runemorten for the feedback 👍  We should provide the user with an easy to understand error message stating that the yaml format does not support tabs, when tabs are included in the configuration file.
