### ISSUE TITLE
Matplotlib-plots in webviz

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz-config#139]
I would be nice to have the opportunity to include matplotlib (and bokeh) plots in the framework. That would give more flexibility and also the opportunity to re-use old code.

**Comment by HansKallekleiv** [comment]
There is a function to convert matplotlib plots to plotly that can be used for simple plots.
https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/tools.py#L75


Example:
```python
import matplotlib.pyplot as plt
import plotly.tools as tls

import dash
import dash_core_components as dcc

from webviz_config import WebvizContainerABC
from webviz_core_components import Graph


class MplExample(WebvizContainerABC):
    """### MplExample
    
"""

    def __init__(self, app):
        fig, ax = plt.subplots()
        ax.plot([1, 2, 3], [1, 4, 9], "o")
        self.plotly_fig = tls.mpl_to_plotly(fig)

    @property
    def layout(self):
        return Graph(figure=self.plotly_fig)
```

Alternatively it can be included as an image, which seems to be the prefered method by plotly:
https://community.plot.ly/t/best-way-to-incorporate-matplotlib-plot-in-dash-app/12896

**Comment by anders-kiaer** [comment]
Closing this - based on answer from Hans it appears there are workarounds already in the Dash community.
