### ISSUE TITLE
General container settings

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-config#160]
`webviz-config` has, in the configuration file, a dictionary called `container_settings` which are there for the user to set general configurations, shared between multiple containers.

The individual containers can ask for this dictionary, and take out the values they need (for a given predefined key). However - it would be useful if `webviz-config` had somewhat more knowledge about the structure of `container_settings`:

- If `webviz-config` knows the types of the different elements going in, it can do transformations (e.g. go from a string being a path relative to the configuration file, to an absolute `Path` instance).
- If the containers has some checks they want to perform on the dictionary `containers_settings`, they can do that early in the app startup process.
- `webviz-config` can potentially detect conflicts between different third-party containers requesting and (re)defining the same key in `container_settings`.

**Comment by anders-kiaer** [comment]
This is related to, and inspired by, https://github.com/equinor/webviz-subsurface/issues/128.

**Comment by anders-kiaer** [comment]
Since the nature of `container_settings` is common settings shared between containers, I don't think it makes sense to create a "subscribe to container settings" method in the containers (as that would require duplication of code).

Maybe instead on package level (e.g. `webviz-subsurface`) there could be a decorated function which registers which settings that package might want to use, together with corresponding types, and potentially also functions that should be called for simple error checks (like "does this path exist"?)

Thoughts @HansKallekleiv?

**Comment by HansKallekleiv** [comment]
Sounds good!  If it is possible as you say to have a function at package level that provides the settings and types that would be very flexible and useful 👍
