### ISSUE TITLE
Increase list of whitelisted html tags in markdown

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-config#168]
We currently have a quite [short list of whitelisted `html` tags](https://github.com/equinor/webviz-config/blob/25582b1112547008daf66cd83de222daf29dd918/webviz_config/containers/_markdown.py#L98-L138) allowed in user provided markdown text.

The list given to [`bleach`](https://github.com/mozilla/bleach) could be extended without adding any risks. E.g. also allowing `<details>` and `<summary>` will make some use cases possible, without changing the risk picture.

Tags to add:
 - `details`, attributes allowed: `[open]`.
 - `summary`
- `dl`
- `pre`
- `s`
- `mark`
- `del`
- `ins`
- `q`
- `cite`

Tags to remove:
- `tt` ([deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt)).

Attributes to get more attributes:
- `ol`: `[reversed, start, type]`
- `li`: `[value]`
- `th`: `[colspan, rowspan, scope]`
- `td`: `[colspan, rowspan]`

**Comment by alifbe** [comment]
Details and summary will great addition to the whitelist. In our project, we are visualizing sensitivity of a lot of parameters. 

As it is now, there is a lot of scrolling when we want to compare different sensitivity value and it looks a bit messy too. Having ```<details>``` and ```<summary>``` will potentially improve presentation of the page. 

For ```<details>```, can we allow attribute ```open``` and ```close```?

**Comment by anders-kiaer** [comment]
Thanks @alifbe, good suggestion. Added `open` to allowed suggested attributes for `details`. According to [MDN web docs] `details` only has `open` as attribute (the rest are global ones), and that it is closed by default if `open` is not provided.
