### ISSUE TITLE
Adding firefox as one of the "preferred" browsers

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-config#171]
Should also which browser that is preferred to be opened be added e.g. as a command line option?

Giving e.g. `systemdefault` could give the system default (which `webviz-config` by default is _not_ using, because a lot of our internal users are using very arcane default browsers on RHEL6).

**Comment by tralsos** [comment]
Yes, would be nice to have it as a command line option.

**Comment by anders-kiaer** [comment]
I think along these lines, that we add a subcommand `webviz preferences` which
1. Without any arguments print current user preferences (if set previously).
2. With arguments, the user can update preferred settings, like
```
webviz preferences --browser firefox --theme equinor
```
and then these are picked up when doing e.g. `webviz build`. In this way browser/theme does not need to be provided on each `webviz build` command.

**Comment by anders-kiaer** [comment]
Closed by #202.
