### ISSUE TITLE
Markdown from files

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-config#18]
A user wants to render a markdown text file
Currently markdown can be added as individual lines in the config file. This gets messy for large sections of text.

- [ ] Add container that reads markdown files
- [ ] Add support for images (if possible)

**Comment by anders-kiaer** [comment]
I think it is a good addition.

The path to a given markdown file listed in the configuration file should probably be given by the user as either absolute path, or relative to the configuration file.

Should e.g. images or other resources stated in the included _markdown files_ linked to through the configuration files be _relative to the markdown file_ it is used in, or _relative to the configuration file_ where the markdown file is imported?

From developers point of view I guess the former is most common (i.e. imports are relative to the file actually requesting the imports). Will it be also the best option for the webviz-config end-user?
