### ISSUE TITLE
Webviz on Windows

### ISSUE THREAD

**Issue by eoia** [equinor/webviz-config#213]
Kudos for setting up a very interesting tool. Please excuse if I my first-time issue is not following guidelines.

I have listed a few workarounds in order to make webviz run on Windows. It would be great with some comments on the "hacks" listed below. 

I have an Anaconda distribution installed on a Win10 machine, and activated a python 3.7 environment, details below. Then installed ```webviz-config``` (and ```webviz-core-components```) via ```pip install``` without errors. In addition cloning the webviz-config repository to get a local copy of the example folder for testing.

When trying to get the example to work, a few errors was encountered:
```webviz build ./examples/basic_example.yaml --portable ./my_portable_app```

Hacks to make this run:
1. Change ```python3``` to ```python``` in ```_build_webviz.py```. I guess there are options in Windows to add aliases instead, but didn't go that route ("Manage App Execution Aliases")
2. Adding ```WindowsPath``` to import statement in jinja2-template files to make ```copy_config.py``` work: ```from pathlib import Path, PosixPath, WindowsPath``` added to ```copy_data_template.py.jinja2``` and ```webviz_template.py.jinja2```
3. (not critical) Description regarding certificates, it seems that Chrome requires self-signed certificates to be installed under "Trusted Root Certification Authorities" not under "Personal" as suggested in the stepwise instruction when running ```webviz certificates```

(py37) C:\WINDOWS\system32>python
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:18:50) [MSC v.1900 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by anders-kiaer** [comment]
Thanks for the report @eoia!

> Change `python3` to `python` in `_build_webviz.py`.

Yes, this I would almost say is a small bug, we should use the default `python` (especially now that Python 2 has EOL). It might be that we get rid of some of the `subprocess` calls later as well (when #200 is done).

 > Adding `WindowsPath` to import statement in jinja2-templates [...] `copy_data_template.py.jinja2` and `webviz_template.py.jinja2`.

I think this is perfectly fine change. I see that `WindowsPath` is a subclass of `Path`, and also that it can be imported on Linux machines 👍 

> (not critical) Description regarding certificates

Thanks for notifying. I will add this info to #88.

**Comment by anders-kiaer** [comment]
@eoia: If you could confirm that the changes in #214 is indeed what you needed to do on Windows, that would be great. (In a not so distant future, we btw. probably will add Windows to the CI matrix as well)

**Comment by eoia** [comment]
@anders-kiaer I had just a manual look at the modifications performed on the 4 changed files in #214. These are consistent with changes that works on Windows on my side. Please let me know if I you need some more actions from my side.
