### ISSUE TITLE
Missing first line when using SyntaxHighlighter plugin

### ISSUE THREAD

**Issue by alifbe** [equinor/webviz-config#221]
For some reason, I am missing the first line when using SyntaxHighlighter.

![image](https://user-images.githubusercontent.com/11570927/79829190-b7370b80-83a2-11ea-9a22-168f785f8a57.png)

![image](https://user-images.githubusercontent.com/11570927/79829329-0b41f000-83a3-11ea-85c3-5f252d78bacc.png)

**Comment by anders-kiaer** [comment]
Thanks @alifbe for the report 👍

I _think_ this is an upstream issue with either `dash-core-components`, or perhaps even more upstream (`highlight.js`, `react-markdown`...). We will investigate.

**Comment by asnyv** [comment]
@akia It is not an upstream issue, it is the ``` code block wrap in `_syntax_highlighter.py` which requires new line before and after the code block. Adding a `\n` before and after the `{get_path....}` seems to fix it. (just lucky now that `basic_example.yaml` ends with a `\n`). I will add the fix now.

**Comment by anders-kiaer** [comment]
Nice 👍 Example that you only need one line of logic/code, building on something else, to introduce a bug.
