### ISSUE TITLE
Expose instance of `WebvizRunMode` during build and runtime

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-config#249]
Plugins may have code in their` __init__` method which isn't required to run when building portables. E.g. if their are methods called during `__init__` which are also included in `add_webvizstore`, the code will be executed twice during portable build.

For the examples in `webviz-config`, the gain is negligable, but when processing large datasets in `webvizstore`-decorated functions, the difference in build time may be significant.

**Comment by mhwaage** [comment]
We had a related use case when loading a plugin that called an API during __init__. During build, the client secrets needed to call the API were not present, causing an exception to be raised and failing the build. 

As a workaround, we created a dummy callback that only triggers when the plugin loads, but this is a bit hacky.

A possibility would be to keep calls that can throw in a `@classmethod` constructor (with a 'magic' name). Then webviz can selectively use that constructor (if it exists) when launching, while only loading `__init__` when building.

**Comment by anders-kiaer** [comment]
@sigurdp's introduction of `WebvizRunMode` I think is clever and could enable us to solve both @asnyv's and @mhwaage's use case.

The instance of `WebvizRunmode` (initiated and configured by `webviz-config` early in the app/build startup process) could perhaps be made available through `from webviz_config[...] import thisinstance`. Then it can be used both in plugin `__init__` functions and other places it might be useful. `flask` itself has `from flask import g` which is quite similar wrt. holding general information about the app (https://flask.palletsprojects.com/en/2.0.x/appcontext/).

**Comment by jin-queen** [comment]
The MARS project use the webviz plugin and also the shared_settings keys, given [here](https://github.com/equinor/webviz-config/blob/master/CONTRIBUTING.md#common-settings). 
We would like to access these shared_settings outside the webviz plugin, so that we can "subscribe"/access to these settings in other parts of our code (and that they are read only once).
