### ISSUE TITLE
webviz console script raises AttributeError when called without arguments in Python 3.x

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz-config#254]
Suggest adding an `except` to catch `AttributeError`s and prompt a warning stating that too few arguments have been passed.

See: https://bugs.python.org/issue16308

**Comment by anders-kiaer** [comment]
Thanks for a good suggestion @rubenthoms - new users are likely to run without any arguments the first time, and they should not be faced with an `AttributeError`. Looking at the provided link, there also seems to be a way of setting subparser as required. Maybe that could work as well?
