### ISSUE TITLE
Add pie chart option to TablePlotter

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-config#297]
**Is your feature request related to a problem? Please describe.**
Add pie chart option to `TablePlotter`

**Describe the solution you'd like**
Possibility to plot pie charts based on a table/dataframe (already available as `pie` in `Plotly`)

**Describe alternatives you've considered**
Separate plugin for pie charts, but think it should be quite easy to expand the `TablePlotter` with this option

**Comment by robpoll** [comment]
I'd like to take this issue.

**Comment by robpoll** [comment]
When I open the webviz webapp and I click on Plot a Table I should have a pie chart plot type here. 
That's what I have to implement here, right @asnyv ?

**Comment by asnyv** [comment]
Yep @robpoll 😊 you probably need some logic on what sort of selectors that are relevant for a pie chart (similar to how the selectors change based on the other plot types).

**Comment by robpoll** [comment]
I added the option of a pie chart in tableplotter. Right now, it's pretty rough. Only one choice for what data to visualise based on columns which consists only numerical data.

How can I know when is the issue complete? @asnyv

**Comment by asnyv** [comment]
could you create a pull request for it @robpoll? Then we can see your code, and test it if it's ready for that. 😄

**Comment by robpoll** [comment]
I'd like to add more details to it, like I said, it's pretty rough atm :D 
Anyways, how can I create a PR? It's my first contribution on github, and I'm pretty much lost. @asnyv

**Comment by robpoll** [comment]
After the latest pull my implementation doesn't work. Changing the _table_plotter.py under generic plugins doesn't seem to affect anything. @asnyv

**Comment by asnyv** [comment]
hmm, you might have to rerun `pip install -e .` when you are in the main folder then @robpoll (same folder as `setup.py` is located in) [see the installation guide.](https://github.com/equinor/webviz-config#installation)

When it comes to creating a PR: It seems like you haven't forked this repository yet? In that case [read this small guide](https://guides.github.com/activities/forking/#:~:text=After%20using%20GitHub%20by%20yourself,contribute%20to%20someone%20else's%20project.&text=Creating%20a%20%E2%80%9Cfork%E2%80%9D%20is%20producing,repository%20and%20your%20personal%20copy.) on what a fork is, how to clone it, stage/commit changes and making a pull request. And if you have any questions after that, let me know :)

**Comment by robpoll** [comment]
Running `pip install -e . ` fixed the issue. I have created a PR but I haven't created tests yet and such. @asnyv
