### ISSUE TITLE
Metadata shown through parent container

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-config#37]
Based on an idea from @perolavsvendsen. The base class for `WebvizContainers` could perhaps facilitate showing metainformation like:
- What is the data source?
- Who to contact for more detailed information?
- A [guided tour](https://reactour.js.org/) in the more complex containers (using more text than what is practical to always show/include in e.g. a plot).

**Comment by HansKallekleiv** [comment]
Yes :+1: 
Perhaps a button toolbar that can be wrapped around a container and a general modal/popup that can be attached to the different buttons to display various information.

A guided tour would also be very useful. The question is if we can inject a React tour component to navigate around the different webviz containers. Worth investigating!
