### ISSUE TITLE
Changing the logo

### ISSUE THREAD

**Issue by saeedfb** [equinor/webviz-config#370]
Hi, 
Thanks for the great application you are developing there. I am wondering if it is possible to change the WEBVIZ logo. I'm developing a prototype with Webviz-config and would like to replace the default logo, but unfortunately I could find my way to do so. Highly appreciate the help.

**Comment by asnyv** [comment]
Hi @saeedfb!

Yes, that is possible as part of a theme. 

I am not sure if you use the default `webviz`, or a custom theme like e.g. the `equinor` theme? 

The default `webviz` theme is defined [here](https://github.com/equinor/webviz-config/tree/master/webviz_config/themes).
While an example of a custom theme, the `equinor` theme, is implemented [here](https://github.com/equinor/webviz-config-equinor/tree/7a1ce568c820f78090db506e24a86ed3b0889089/webviz_config_equinor)

In the assets folders you will see some css files, the `default_theme` refers to a local logo file called `default_logo.svg`, while the `equinor` theme refers to a logo hosted on the web through an `url`.

A more hacky way in portables would probably be to include an additional logo file in the `assets` folder and change out the url in the css. But I would not recommend that...

I moved this issue to `webviz-config`, as `webviz-subsurface` is a plugin project, while the `webviz` framework, and the code to e.g. change theme/logo, is located in `webviz-config`.

**Comment by saeedfb** [comment]
Thanks alot Asgeir. I managed to change it based on your guidance. have a nice holiday 👍

**Comment by asnyv** [comment]
You too! I'm closing this then. 👍
