### ISSUE TITLE
Specifying log level for webviz build does not work as expected

### ISSUE THREAD

**Issue by sigurdp** [equinor/webviz-config#434]
Specifying the wanted log level on the command line when doing `webviz build` does not have any effect.

The following command line should set log level to `INFO` but currently this does not happen:
```
webviz build ../webviz-subsurface-testdata/webviz_examples/webviz-full-demo.yml --loglevel INFO
```
Note that fixing this issue will most likely trigger a new need for filtering of log messages from underlying modules since once we're able to set the global log level to `INFO` or `DEBUG`, the log will most likely be flooded with messages.

**Comment by sigurdp** [comment]
Some initial experiments indicate that the core issue may be resolved by making sure that something like this gets called before any other logging calls in our jinja2 templates
```
logging.basicConfig(level=logging.{{ loglevel }})
```

**Comment by sigurdp** [comment]
Possible syntax for logger specific levels: 
`ros2 run logging_demo logging_demo_main --ros-args --log-level debug`
`ros2 run logging_demo logging_demo_main --ros-args --log-level logger_usage_demo:=debug`
(from https://docs.ros.org/en/foxy/Tutorials/Logging-and-logger-configuration.html#logger-level-configuration-command-line)

**Comment by anders-kiaer** [comment]
An easy alternative to how `ros` does it could perhaps be `--log-level` accepting a user provided YAML config for logging configuration (if more detailed instructions are needed).

There is an example of YAML input config in the Python std.docs (bottom part of section https://docs.python.org/3/howto/logging.html#configuring-logging).

**Comment by sigurdp** [comment]
Will concentrate this issue on fixing the bug. 
Enhancing logging granularity split into new issue: https://github.com/equinor/webviz-config/issues/439
