### ISSUE TITLE
GUI for confiugration/help setting up webviz configuration file

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-config#504]
A web GUI for help setting up (or modify existing) `webviz-config` configuration files would be useful.

- We already have JSON schema that can be used...
- ...so maybe https://github.com/rjsf-team/react-jsonschema-form can give a good starting point?
- First iteration scope: Simply help setting up the configuration file, and show e.g. what the resulting menu/overall layout will be, and for the plugins themselves you only show some styled placeholder `divs` (with e.g. plugin title).
  - Later iterations could, if found worth the effort, try doing live start/restart/reload of the resulting Dash/Webviz application. This might face the same issue as behind https://github.com/plotly/dash/pull/1246 though.

We might want to do https://github.com/equinor/webviz-config/issues/357 first (especially `@typing.overload` there will provide useful information to the generated json schema, which will be valuable input to the GUI tool).

**Comment by anders-kiaer** [comment]
To start the editor, we could perhaps see something like `webviz config [existing-file-if-the-user-has.yaml]`, which opens a non-Dash based localhost server with the GUI editor (`webviz docs` is an example of non-Dash based localhost server, in that case purely based on https://docsify.js.org/#/ + static server).

**Comment by anders-kiaer** [comment]
@rubenthoms also had a good idea/possibility: we might be able to reuse the web GUI as a VS code extension (a random example of file-to-live-preview: https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview)

**Comment by rubenthoms** [comment]
We implemented the first version of an editor which meets the above-mentioned requirements. The repo of the webviz-config-editor can be found here: github.com/equinor/webviz-config-editor. Hence, I am closing this issue. Any objections, @anders-kiaer?
