### ISSUE TITLE
BannerImage plugin -  title option

### ISSUE THREAD

**Issue by rnyb** [equinor/webviz-config#530]
The  BannerImage `title` will place text in center of image. 
Consider adding options to place text at top or bottom of image?

**Comment by izzy-el** [comment]
Hey! Can I take this issue?

**Comment by anders-kiaer** [comment]
If you want to give it a try, that is great @izzy-el.

**Comment by izzy-el** [comment]
Thank you @anders-kiaer. I was abled to implement this feature by adding a new argument `title_position` where the user can specify if they want it to be placed on the top of the image or on the bottom (`center` is the default). However, I am not sure how I can add tests to check this. I tried and executed in my browser and it is working fine. Do you have any suggestions on how to approach this?

**Comment by anders-kiaer** [comment]
Sounds good. We don't really have any good test setups for visual regression. Currently there are selenium tests mostly for checking that it renders without errors, but we have plans for adding visual regression tests like e.g. percy or similar. We are okey with not adding visual tests for this feature (as of now). 🙂
