### ISSUE TITLE
Latest `flask-caching` gives problems with `mypy`

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-config#595]
Similar to https://github.com/equinor/webviz-subsurface/issues/1043.

**Comment by asnyv** [comment]
Propose to rather follow this: https://flask-caching.readthedocs.io/en/latest/#set-up

So skip the current `CACHE.TIMEOUT = 3600` followed be `timeout=TIMEOUT` in the cache decorators and rather initialize the common cache with:
`CACHE = flask_caching.Cache(config={"CACHE_TYPE": "simple", "CACHE_DEFAULT_TIMEOUT": 3600})`
